### ISSUE TITLE
Can I use command submenus?

### ISSUE THREAD

**Issue by abargnesi** [formwork-io/gosh#7]
I would like to group commands into sub-menus for a hierarchical structure. Something like:

    1: docs

        - api
        - rest

    2: server

        - start
        - stop
        - restart

    3: test

        - api
        - rest

Can I use sub-directories within `GOSH_SCRIPTS` to group commands by sub-menu name?

**Comment by nbargnesi** [comment]
Short answer, no. It sounds like you're describing a feature driven by the mere existence of subdirectories. That seems like a useful feature.

What you *can do*, is include submenus where the ``GOSH_SCRIPTS`` can exist anywhere, *including* a subdirectory within ``GOSH_SCRIPTS``. This is how the submenu is built in the [current set of examples](https://github.com/formwork-io/gosh/tree/v0.3/examples).

([an asciicast exercising the current submenu functionality](https://asciinema.org/a/15697))
